---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: NetApp Console ローカル展開の一部である機能とデータサービスへの最新の変更点について説明します。 
---
= NetApp Console ローカル展開の最近の変更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console ローカル展開の一部である機能とデータサービスへの最新の変更点について説明します。



[[21-september-2026]]
== 2026年9月21日



[[backup-and-recovery]]
=== バックアップとリカバリ



==== Kubernetes ワークロードの機能強化

今回のリリースでは、Kubernetesワークロードに以下の機能強化が導入されました。

* *Trident Protect 26.09*：このリリースには Trident Protect 26.09 が含まれます。
* *クラスタおよび名前空間単位のロールベースのアクセス制御*：Kubernetesクラスタの検出中に、新しいクラスタに関連付けるプロジェクトまたはフォルダを選択することで、リソースへのアクセスを制御できます。アクセス制御のために、特定の名前空間を登録することもできます。これにより、クラスタレベルまたはネームスペースレベルで、よりきめ細かなアクセス制御が可能になります。
* *ファイルとフォルダの復元*：Kubernetes VM ベースのアプリケーションバックアップから、特定のファイルとフォルダを復元またはダウンロードできるようになりました。


Kubernetesワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["NetApp Backup and Recoveryを使用したKubernetesワークロードの保護について説明します"]を参照してください。



[[16-september-2026]]
== 2026年9月16日



[[backup-and-recovery]]
=== バックアップとリカバリ



==== 一般的なNetApp Backup and Recoveryの機能強化

今回のリリースでは、KVM、Hyper-V、およびVMwareワークロードに以下の機能強化が導入されました：

*VM ホスト検出時の認証情報の選択*：KVM、Hyper-V、または VMware ホストを検出する際に、Backup and Recovery に既に追加済みの認証情報を使用できるようになりました。



==== Hyper-Vワークロードの機能強化

今回のリリースでは、Hyper-Vワークロードに以下の機能強化が導入されました。

*VM のスパンディスク保護*: CIFS 構成の場合、Backup and Recovery は、保護グループ内の各 VM に接続されているすべてのディスクを保護できるようになりました。これには、複数の ONTAP ボリュームまたは ONTAP ストレージシステムに分散したファイル（スパンディスク）と、単一の場所に限定されたファイルが含まれます。

Hyper-Vワークロードの保護に関する詳細は、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Hyper-VワークロードをNetApp Backup and Recoveryで保護する方法について説明します"]を参照してください。



==== ONTAPボリュームワークロードの強化

今回のリリースでは、ONTAP Volumes ワークロードに、以下のプレビュー版機能強化が導入されました。

*日次バックアップデータ転送レポート*：NetApp Backup and Recovery for Volumes の「レポート」タブに日次バックアップデータ転送レポートが追加されました。これにより、環境全体における日々のバックアップおよびレプリケーションのデータ転送状況を把握できます。アカウント全体または選択したストレージシステムについてレポートを生成し、日付範囲と保護タイプでフィルタリングして、結果をCSV形式でダウンロードできます。

ONTAP ボリュームワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recoveryを使用したONTAPボリューム保護について説明します"]を参照してください。



[[17-august-2026]]
== 2026年8月17日



[[backup-and-recovery]]
=== バックアップとリカバリ



==== Hyper-V ワークロードの機能強化

今回のリリースでは、Hyper-Vワークロードに以下の機能強化が導入されました。

*オブジェクトストレージのバックアップを別の場所に復元する*：Hyper-V の仮想マシン、ファイル、フォルダーをオブジェクトストレージから別のストレージ場所に復元できるようになりました。

Hyper-Vワークロードの保護に関する詳細は、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Hyper-VワークロードをNetApp Backup and Recoveryで保護する方法について説明します"]を参照してください。



==== Kubernetes ワークロードの機能強化

今回のリリースでは、Kubernetesワークロードに以下の機能強化が導入されました。

* *Trident Protect 26.08*：このリリースには Trident Protect 26.08 が含まれます。
* *バックアップの再試行*：Kubernetes 保護ポリシーの詳細設定で、バックアップの再試行を有効にし、再試行回数と再試行間隔を設定できるようになりました。
* *部分的なバックアップの成功*：Kubernetes の保護ポリシーの詳細設定で、個々のリソースが失敗した場合でもバックアップを継続するように構成できるようになり、バックアップジョブが部分的に成功した状態として完了できるようになります。これにより、バックアップ操作中に一部のリソースが失敗した場合でも、バックアップされたリソースを復元することができます。
* *「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態およびVM一貫性のバックアップ*：Backup and Recovery for NetApp Consoleサービスで、「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態またはVM一貫性のバックアップやスナップショットを作成する保護ポリシーを設定できるようになりました。また、保護処理中にVMのフリーズを実行する方法をカスタマイズすることもできます。
* *ConsoleエージェントのIPアドレス変更時のKubernetesクラスターの再接続*：Backup and Recovery for NetApp Consoleサービスでは、エージェントのIPアドレスが変更された場合に、クラスターをそのConsoleエージェントに再接続できるようになりました。
* *クラスターを新しいコンソールエージェントに移行する*：NetApp Backup and Recovery コンソールサービスでは、元のエージェントが故障または削除された場合に、クラスターを新しいコンソールエージェントに移行できるようになり、アプリケーションの保護が中断なく継続されます。


Kubernetesワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["NetApp Backup and Recoveryを使用したKubernetesワークロードの保護について説明します"]を参照してください。



==== Oracle Databaseワークロードの強化

今回のリリースでは、Oracle Databaseワークロードに以下の機能強化が導入されました：

* *プラガブルデータベース（PDB）の復元*：個々のプラガブルデータベース（PDB）および PDB テーブルスペースを、ポイントインタイムリカバリを含めて復元できるようになりました。
* *プラガブルデータベース（PDB）クローン*：既存のターゲットコンテナデータベース（CDB）に単一のPDBをクローンできるようになりました。また、コンテナデータベース全体をクローンする際に、PDBを除外することも可能です。


Oracle Databaseワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["NetApp Backup and Recovery を使用した Oracle Database ワークロードの保護について学ぶ"]を参照してください。



[[10-august-2026]]
== 2026年8月10日



[[netapp-console-local-deployment]]
=== NetApp Console ローカル展開



==== NetApp Consoleローカル デプロイのご紹介

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["NetApp Console ローカル展開について学ぶ"]。

https://docs.netapp.com/us-en/console-local/console-differences.html["NetApp Console ローカル展開とNetApp Console SaaS およびプライベートモードの違いについて説明します"]。



[[backup-and-recovery]]
=== バックアップとリカバリ



==== 一般的なNetApp Backup and Recovery の機能強化

* *NetApp Console ローカル展開のサポート*：このリリースの NetApp Backup and Recovery は、プレビュー ステータスの NetApp Console ローカル展開をサポートしています。
* *90日間のジョブ保持*：Backup and Recovery では、ジョブモニター内のジョブ情報が90日間保持されるようになりました。




==== VMwareワークロードの機能強化

今回のリリースでは、VMwareワークロードに以下の機能強化が導入されました：

* *SAN VM の代替場所への復元サポート*：SAN ベースの VM バックアップを代替場所に復元できるようになりました。
* *複数バックアップの削除に対応*：複数のバックアップを一度に削除できるようになりました。


VMwareワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["VMware ワークロードの保護の概要"]を参照してください。



==== Kubernetes ワークロードの機能強化

今回のリリースでは、Kubernetesワークロードに以下の機能強化が導入されました。

* *エアギャップされたリソースのプレビューサポート*：NetApp Console のローカルデプロイメントで NetApp Backup and Recovery を実行している場合、エアギャップされた Kubernetes リソースを検出、保護、および復元できます。この機能は今回のリリースではプレビュー版です。


Kubernetesワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Kubernetes ワークロードの保護の概要"]を参照してください。



==== ONTAP ボリュームワークロードの機能強化

今回のリリースでは、ONTAP Volumes ワークロードに以下の機能強化が導入されました。

* *バックアップよりも復元ジョブを優先*：ボリューム、ファイル、またはフォルダーを復元する際に、バックアップジョブよりも復元ジョブを優先できるようになりました。
* *Backup and Recovery をアクティブ化せずに ONTAP システムとボリュームを検出*：Backup and Recovery をアクティブ化しなくても、システムとボリュームを検出できるようになりました。


ONTAP ボリュームワークロードの保護の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["ONTAP ボリュームワークロードの保護の概要"]を参照してください。



[[13-july-2026]]
== 2026年7月13日



[[backup-and-recovery]]
=== バックアップとリカバリ



==== すべてのワークロードに対するマルチバケットサポートの強化

NetApp Backup and Recovery は、異なるクラウドプロバイダーにまたがる最大 100 個のバケットを使用して、システム内のワークロードを保護する機能をサポートするようになりました。システムあたり 6 つを超えるバケットをサポートするには、ONTAP 9.19.1 以降が必要です。

NetApp Backup and Recovery の詳細については、 https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["NetApp Backup and Recovery について"]を参照してください。
